@host = http://localhost:{{$dotenv SERVER_PORT}}/api/admin

### Login
POST {{host}}/login
Content-Type: application/json

{
    "display_name": "",
    "password": ""
}

### Get unapproved documents
POST {{host}}/get-unapproved-documents
Content-Type: application/json

{
    "pagination": {
        "page": 0,
        "perPage": 0
    },
    "keyword": "",
    // Timestamp in milliseconds
    "filter": 0 
}

### Get document detail
POST {{host}}/get-document-detail
Content-Type: application/json

{
    "document": 0
}

### Review document
POST {{host}}/review-document
Content-Type: application/json

{
    "document": 0,
    "isApproved": false,
    "reason": ""
}
