@host = http://localhost:{{$dotenv SERVER_PORT}}/api/course

### Create course
POST {{host}}/create-course
Content-Type: application/json

{
    "title": ""
}

### Get courses
POST {{host}}/get-courses
Content-Type: application/json

{
    "keyword": ""
}
