@host = http://localhost:{{$dotenv SERVER_PORT}}/api/document

### Create document
POST {{host}}/create-document
Content-Type: application/json

{
    "title": "",
    "description": "",
    "course": 0,
    "questions": [
        {
            "correct": "",
            "contents": [
                {
                    "text": "",
                    "attachment": "",
                    "type": "Q"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "A"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "B"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "C"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "D"
                }
            ]
        }
    ]
}

### Get document detail owner
POST {{host}}/get-document-detail-owner
Content-Type: application/json

{
    "document": 0
}

### Get document detail guest
POST {{host}}/get-document-detail-guest
Content-Type: application/json

{
    "document": 0
}

### Delete document
DELETE {{host}}/delete-document
Content-Type: application/json

{
    "document": 0
}

### Edit document
PATCH {{host}}/edit-document
Content-Type: application/json

{
    "document": 0,
    "title": "",
    "description": "",
    "course": 0,
    "questions": [
        {
            "action": "add",
            "order": 0,
            "correct": "",
            "contents": [
                {
                    "text": "",
                    "attachment": "",
                    "type": "Q"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "A"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "B"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "C"
                },
                {
                    "text": "",
                    "attachment": "",
                    "type": "D"
                }
            ]
        },
        {
            "action": "delete",
            "id": 0
        },
        {
            "action": "edit",
            "id": 0,
            "order": 0,
            "correct": "",
            "contents": [
                {
                    "id": 0,
                    "text": "",
                    "attachment": ""
                }
            ]
        }
    ]
}

### Get documents
POST {{host}}/get-documents
Content-Type: application/json

{
    "pagination": {
        "page": 0,
        "perPage": 0
    },
    "keyword": "",
    // Timestamp in milliseconds
    "filter": 0 
}
