@host = http://localhost:{{$dotenv SERVER_PORT}}/api/practice

### Get document forr practice
GET {{host}}/getdocsforprac/?keyword=00&page=2&limit=4&course_id=1

### Get document forr practice
GET {{host}}/getpracticehistory/?page=3&limit=7
