@host = http://localhost:{{$dotenv SERVER_PORT}}/api/user

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Logout
POST {{host}}/logout
Content-Type: application/json

### Verify email
POST {{host}}/verifyemail
Content-Type: application/json

{
    "email": ""
}

### Register
POST {{host}}/register
Content-Type: application/json
Cookie: accessToken=

{
    "display_name": "",
    "password": "",
    "confirmPassword": ""
}

### Forget password
POST {{host}}/forgetpassword
Content-Type: application/json

{
    "email": ""
}

### Reset password
POST {{host}}/resetpassword
Content-Type: application/json

{
    "newPassword": "",
    "confirmNewPassword": ""
}

### Change password
POST {{host}}/changepassword
Content-Type: application/json

{
    "oldPassword": "",
    "newPassword": "",
    "confirmNewPassword": ""
}

### Update info
PATCH {{host}}/update
Content-Type: application/json

{
    "new_display_name": ""
}

### Get info
GET {{host}}/showinfo
Content-Type: application/json

### Refresh token
POST {{host}}/refreshtoken
Content-Type: application/json
