CREATE TYPE "correct_answer_type" AS ENUM (
  'A',
  'B',
  'C',
  'D'
);

CREATE TYPE "content_type" AS ENUM (
  'A',
  'B',
  'C',
  'D',
  'Q'
);

CREATE TYPE "arena_status" AS ENUM (
  'Thắng',
  'Hòa',
  'Thua'
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" VARCHAR(64) NOT NULL,
  "email" VARCHAR(256) UNIQUE NOT NULL,
  "password" VARCHAR(256) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "last_updated" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "courses" (
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE "documents" (
  "document_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(256) NOT NULL,
  "description" VARCHAR(2048),
  "total_question" INT NOT NULL,
  "course_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "last_updated" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "is_approved" BOOLEAN NOT NULL DEFAULT false,
  "admin_id" INT,
  "reject_reason" VARCHAR(2048)
);

CREATE TABLE "questions" (
  "question_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order" INT NOT NULL,
  "correct_answer" correct_answer_type NOT NULL
);

CREATE TABLE "contents" (
  "content_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" VARCHAR(4096),
  "attachment" BYTEA,
  "type" content_type NOT NULL,
  "question_id" INT NOT NULL
);

CREATE TABLE "document_questions" (
  "document_id" INT,
  "question_id" INT,
  PRIMARY KEY ("document_id", "question_id")
);

CREATE TABLE "practice_histories" (
  "practice_history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "score" REAL NOT NULL,
  "detail" BYTEA NOT NULL,
  "user_id" INT NOT NULL
);

CREATE TABLE "arena_histories" (
  "arena_history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "status" arena_status NOT NULL,
  "detail" BYTEA NOT NULL,
  "user_id" INT NOT NULL,
  "opponent" INT NOT NULL
);

CREATE TABLE "admins" (
  "admin_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" VARCHAR(64) UNIQUE NOT NULL,
  "password" VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX ON "contents" ("type", "question_id");

CREATE UNIQUE INDEX ON "practice_histories" ("created_at", "user_id");

CREATE UNIQUE INDEX ON "arena_histories" ("created_at", "user_id");

CREATE UNIQUE INDEX ON "arena_histories" ("user_id", "opponent");

ALTER TABLE "contents" ADD CHECK ("text" IS NOT NULL OR "attachment" IS NOT NULL);

ALTER TABLE "documents" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "documents" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "documents" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("admin_id");

ALTER TABLE "contents" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("question_id") ON DELETE CASCADE;

ALTER TABLE "document_questions" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("document_id") ON DELETE CASCADE;

ALTER TABLE "document_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("question_id") ON DELETE RESTRICT;

ALTER TABLE "practice_histories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "arena_histories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "arena_histories" ADD FOREIGN KEY ("opponent") REFERENCES "users" ("user_id");

